# Generated by Django 2.1.9 on 2020-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Meraki', models.IntegerField()),
                ('Name', models.CharField(max_length=254)),
                ('Wifi_Mac', models.CharField(max_length=254)),
                ('Os_Name', models.CharField(max_length=254)),
                ('System_Model', models.CharField(max_length=254)),
                ('Uuid', models.CharField(max_length=254)),
                ('Serial_Number', models.CharField(max_length=254)),
                ('Data_Plan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehicle', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
            ],
        ),
    ]
