# Generated by Django 2.1.9 on 2020-11-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConectivityInfoDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('meraki_id', models.IntegerField()),
                ('battery_level', models.IntegerField()),
                ('last_connected', models.DateTimeField()),
                ('data_used', models.IntegerField()),
                ('location', models.CharField(max_length=254)),
                ('received_on', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Connectivity info device',
                'verbose_name_plural': 'Connectivity info devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meraki_id', models.CharField(max_length=254)),
                ('vehicle', models.CharField(max_length=254)),
                ('wifi_mac', models.CharField(max_length=254)),
                ('os_name', models.CharField(max_length=254)),
                ('system_model', models.CharField(max_length=254)),
                ('uuid', models.CharField(max_length=254)),
                ('serial_number', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Device Catalogue',
                'verbose_name_plural': 'Device Catalogues',
            },
        ),
    ]
