# Generated by Django 2.1.9 on 2020-12-01 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectivityInfoDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Id', models.IntegerField()),
                ('Meraki_Id', models.IntegerField()),
                ('Battery_Level', models.IntegerField()),
                ('Last_Connected', models.DateTimeField()),
                ('Data_Used', models.IntegerField()),
                ('Location_Device', models.CharField(max_length=254)),
                ('Received_On', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='devicecatalogue',
            name='Id_Meraki',
            field=models.CharField(max_length=254),
        ),
    ]
