# Generated by Django 2.1.9 on 2020-11-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConectivityInfoDevice',
        ),
    ]
