# Generated by Django 2.1.9 on 2020-11-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0002_delete_conectivityinfodevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectivityInfoDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(db_column='Vehicle')),
                ('battery_level', models.IntegerField()),
                ('last_connected', models.DateTimeField()),
                ('data_used', models.IntegerField()),
                ('location', models.CharField(max_length=254)),
                ('received_on', models.DateTimeField()),
                ('meraki_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meraki_devices.DeviceCatalogue')),
            ],
            options={
                'verbose_name': 'Connectivity info device',
                'verbose_name_plural': 'Connectivity info devices',
            },
        ),
    ]
