# Generated by Django 2.1.9 on 2020-12-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0002_auto_20201201_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conectivityinfodevice',
            name='Meraki_Id',
            field=models.CharField(max_length=254),
        ),
    ]
