# Generated by Django 2.1.9 on 2020-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0003_conectivityinfodevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehicle', models.IntegerField()),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='conectivityinfodevice',
            name='meraki_id',
        ),
        migrations.DeleteModel(
            name='ConectivityInfoDevice',
        ),
    ]
