# Generated by Django 2.1.9 on 2020-11-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0004_auto_20201128_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectivityInfoDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.IntegerField()),
                ('last_connected', models.DateTimeField()),
                ('data_used', models.IntegerField()),
                ('location', models.CharField(max_length=254)),
                ('received_on', models.DateTimeField()),
                ('meraki_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meraki_devices.DeviceCatalogue')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meraki_devices.Vehicle')),
            ],
        ),
    ]
