# Generated by Django 2.1.9 on 2020-11-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meraki_devices', '0005_conectivityinfodevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conectivityinfodevice',
            old_name='meraki_id',
            new_name='meraki',
        ),
        migrations.RenameField(
            model_name='conectivityinfodevice',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
